name: main

on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: NPM Install
        run: npm ci --cache ~/.npm --prefer-offline

      - name: Run Linter
        run: npm run lint --if-present -- --no-error-on-unmatched-pattern

      - name: Run Tests
        run: npm run test --if-present -- --ci
