name: version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      message:
        description: Release message
        required: true

jobs:
  version:
    uses: NTTDSP/ui-tooling-actions/.github/workflows/version.yml@main
    secrets:
      UI_GITHUB_PAT: ${{ secrets.UI_GITHUB_PAT }}
